const STORAGE='siteguard152-projects-v1',BRAND='siteguard152-brand-v1';
const $=id=>document.getElementById(id),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||String(Date.now())+Math.random().toString(16).slice(2);
const fields=['projectName','entityType','operatorName','inn','operatorAddress','operatorEmail','responsiblePerson','domain','businessType','retention','siteType','collectName','collectPhone','collectEmail','collectAddress','collectAccount','collectPayment','useAnalytics','useCrm','useMessengers','useNewsletter','useForeign','hasChildren','hasSensitive','hasBiometric','processors','purposes'];
const checks=new Set(fields.filter(x=>x.startsWith('collect')||x.startsWith('use')||x.startsWith('has')));
let projects=[],activeId=null,currentDoc='policy',branding={whiteLabelName:'SiteGuard 152',agencyName:'',agencyContact:'',accentColor:'#86ffb3'};
const clean=v=>String(v??'').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function blank(){return{id:uid(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),projectName:'Новый сайт',entityType:'ИП',operatorName:'',inn:'',operatorAddress:'',operatorEmail:'',responsiblePerson:'',domain:'',businessType:'',retention:'До достижения цели обработки',siteType:'landing',collectName:true,collectPhone:true,collectEmail:false,collectAddress:false,collectAccount:false,collectPayment:false,useAnalytics:true,useCrm:false,useMessengers:true,useNewsletter:false,useForeign:false,hasChildren:false,hasSensitive:false,hasBiometric:false,processors:'',purposes:'Обработка заявок, обратная связь и заключение договора'}}
function demo(){return{...blank(),id:uid(),projectName:'Салон красоты Aurora',entityType:'ООО',operatorName:'ООО «Аврора Бьюти»',inn:'7453000000',operatorAddress:'г. Челябинск, ул. Примерная, д. 10',operatorEmail:'privacy@aurora-beauty.ru',responsiblePerson:'Администратор сайта',domain:'aurora-beauty.ru',businessType:'Салон красоты',siteType:'landing',collectName:true,collectPhone:true,collectEmail:true,useAnalytics:true,useCrm:true,useMessengers:true,useNewsletter:true,processors:'Хостинг-провайдер; CRM; сервис онлайн-записи; сервис рассылок',purposes:'Онлайн-запись, обратная связь, исполнение договора, аналитика и рекламная рассылка'}}
function active(){return projects.find(p=>p.id===activeId)||null}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(projects));localStorage.setItem(BRAND,JSON.stringify(branding))}
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._);t._=setTimeout(()=>t.classList.remove('show'),2100)}
function read(){try{projects=JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{projects=[]}try{branding={...branding,...JSON.parse(localStorage.getItem(BRAND)||'{}')}}catch{}if(!projects.length)projects=[blank()];activeId=projects[0].id;applyBrand();renderAll()}
function toForm(p){fields.forEach(id=>{const e=$(id);if(!e)return;checks.has(id)?e.checked=!!p[id]:e.value=p[id]??''})}
function fromForm(){const p=active();if(!p)return;fields.forEach(id=>{const e=$(id);p[id]=checks.has(id)?e.checked:e.value});p.updatedAt=new Date().toISOString();persist();renderProjects();renderAudit();renderDocs();renderCodes()}
function renderProjects(){const box=$('projectList');box.innerHTML=projects.map(p=>`<button class="project ${p.id===activeId?'active':''}" data-id="${p.id}"><b>${esc(p.projectName||'Без названия')}</b><span>${esc(p.domain||p.operatorName||'Анкета не заполнена')}</span></button>`).join('');qsa('.project',box).forEach(b=>b.onclick=()=>{fromForm();activeId=b.dataset.id;toForm(active());renderAll()})}
function switchTab(name){qsa('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));qsa('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+name));if(name==='audit')renderAudit();if(name==='docs')renderDocs();if(name==='code')renderCodes();window.scrollTo({top:220,behavior:'smooth'})}
qsa('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function dataset(p){const out=[];if(p.collectName)out.push('имя');if(p.collectPhone)out.push('номер телефона');if(p.collectEmail)out.push('адрес электронной почты');if(p.collectAddress)out.push('адрес доставки');if(p.collectAccount)out.push('данные учётной записи и историю действий');if(p.collectPayment)out.push('сведения, необходимые для оплаты и формирования чека');if(p.useAnalytics)out.push('IP-адрес, cookie-файлы и технические сведения');return out.length?out:['данные, добровольно предоставленные пользователем в формах сайта']}
function analyze(p){const issues=[],ok=[],add=(sev,title,text)=>issues.push({sev,title,text});
 if(clean(p.operatorName))ok.push('Указан оператор');else add('critical','Не указан оператор','Заполните полное наименование оператора.');
 if(clean(p.inn)||p.entityType==='Физическое лицо')ok.push('Есть идентификатор оператора');else add('warning','Не указан ИНН','Добавьте ИНН для идентификации оператора.');
 if(clean(p.operatorEmail))ok.push('Есть канал обращений');else add('critical','Нет email для обращений','Укажите адрес для запросов и отзыва согласия.');
 if(clean(p.domain))ok.push('Указан домен');else add('critical','Не указан домен','Привяжите документы к конкретному сайту.');
 if(clean(p.purposes))ok.push('Определены цели');else add('critical','Не определены цели','Перечислите конкретные цели обработки.');
 if(clean(p.processors)||(!p.useCrm&&!p.useNewsletter&&!p.collectPayment&&!p.useForeign))ok.push('Описаны подрядчики');else add('warning','Не перечислены подрядчики','Укажите хостинг, CRM, рассылку и платёжные сервисы.');
 if(p.collectName||p.collectPhone||p.collectEmail||p.collectAddress||p.collectAccount)ok.push('Определён состав данных');else add('warning','Не отмечены собираемые данные','Отметьте фактические поля форм и технические данные.');
 if(p.useAnalytics)add('warning','Используется аналитика и cookies','Разместите cookie-политику и проверьте фактический состав счётчиков.');else ok.push('Аналитические cookies не отмечены');
 if(p.useNewsletter)add('warning','Есть рекламная рассылка','Используйте отдельное добровольное согласие на рекламу.');else ok.push('Рассылка не отмечена');
 if(p.useForeign)add('critical','Используются иностранные сервисы','Проверьте локализацию, трансграничную передачу и договоры.');else ok.push('Иностранные сервисы не отмечены');
 if(p.hasSensitive)add('critical','Обрабатываются специальные категории','Нужна отдельная проверка оснований, доступа и защиты.');else ok.push('Спецкатегории не отмечены');
 if(p.hasBiometric)add('critical','Возможна обработка биометрии','Проверьте цель идентификации и проведите специализированную оценку.');else ok.push('Биометрия не отмечена');
 if(p.hasChildren)add('warning','Есть данные несовершеннолетних','Добавьте процедуры согласия законного представителя.');else ok.push('Несовершеннолетние не выделены');
 add('warning','Проверьте уведомление Роскомнадзора','Оцените обязанность и исключения по фактическим процессам обработки.');
 const value=Math.max(10,Math.min(100,100-issues.reduce((s,x)=>s+(x.sev==='critical'?12:6),0)));return{value,issues,ok}}
function renderAudit(){const p=active();if(!p)return;const s=analyze(p);$('scoreValue').textContent=s.value;$('heroScore').textContent=s.value+'%';$('scoreRing').style.background=`conic-gradient(var(--accent) ${s.value*3.6}deg,#26313e 0deg)`;$('heroBar').style.width=s.value+'%';$('criticalCount').textContent=s.issues.filter(x=>x.sev==='critical').length;$('warningCount').textContent=s.issues.filter(x=>x.sev==='warning').length;$('okCount').textContent=s.ok.length;let title,desc;if(s.value>=85){title='Сильная базовая готовность';desc='Сверьте шаблоны с реальными процессами и подрядчиками.'}else if(s.value>=65){title='Нужны точечные исправления';desc='Рабочая основа есть, но несколько пробелов требуют внимания.'}else{title='Высокий риск неполного пакета';desc='Заполните критичные сведения до публикации документов.'}$('scoreTitle').textContent=title;$('scoreDescription').textContent=desc;$('heroText').textContent=title;$('issueList').innerHTML=[...s.issues,...s.ok.map(x=>({sev:'ok',title:x,text:'Пункт отражён в текущей анкете.'}))].map(x=>`<article class="issue ${x.sev}"><i></i><div><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div></article>`).join('')}
function labels(p){return{operator:clean(p.operatorName)||'[ПОЛНОЕ НАИМЕНОВАНИЕ ОПЕРАТОРА]',domain:clean(p.domain)||'[ДОМЕН САЙТА]',email:clean(p.operatorEmail)||'[EMAIL ДЛЯ ОБРАЩЕНИЙ]',data:dataset(p).join(', '),purposes:clean(p.purposes)||'обработка обращений, обратная связь и исполнение договоров',processors:clean(p.processors)||'лица, привлекаемые оператором на основании договоров и поручений'}}
function docs(p){const l=labels(p),date=new Intl.DateTimeFormat('ru-RU').format(new Date());return{
policy:`ПОЛИТИКА В ОТНОШЕНИИ ОБРАБОТКИ ПЕРСОНАЛЬНЫХ ДАННЫХ\n\nРедакция от ${date}\n\n1. ОБЩИЕ ПОЛОЖЕНИЯ\n\n1.1. Настоящая Политика определяет порядок обработки и защиты персональных данных оператором: ${l.operator}${p.inn?' (ИНН '+p.inn+')':''}.\n1.2. Политика применяется к информации, получаемой через сайт ${l.domain}.\n1.3. Контакт для обращений: ${l.email}.\n1.4. Документ сформирован по анкете и подлежит проверке с учётом фактических процессов.\n\n2. ЦЕЛИ ОБРАБОТКИ\n\n${l.purposes}.\n\n3. КАТЕГОРИИ СУБЪЕКТОВ И ДАННЫХ\n\nСубъектами могут быть посетители сайта, клиенты, заказчики и лица, направившие обращение. В зависимости от формы могут обрабатываться: ${l.data}.\n\n4. ПРАВОВЫЕ ОСНОВАНИЯ\n\nОбработка осуществляется при наличии применимого основания: согласия, необходимости заключения или исполнения договора, исполнения обязанности оператора либо иного основания, предусмотренного законом.\n\n5. ДЕЙСТВИЯ С ДАННЫМИ\n\nСбор, запись, систематизация, накопление, хранение, уточнение, использование, передача уполномоченным получателям, блокирование и уничтожение в пределах заявленных целей.\n\n6. ПЕРЕДАЧА И ПОДРЯДЧИКИ\n\nДля работы сайта и оказания услуг могут привлекаться: ${l.processors}. Передача производится при наличии основания и обязательств по защите данных.\n\n7. COOKIE И ТЕХНИЧЕСКИЕ ДАННЫЕ\n\n${p.useAnalytics?'Сайт может использовать cookie, IP-адрес, сведения о браузере, устройстве и действиях пользователя для работы и аналитики. Пользователь может ограничить cookie в браузере.':'Сайт использует технические данные, необходимые для его работы, если иное не указано в интерфейсе.'}\n\n8. ХРАНЕНИЕ И УНИЧТОЖЕНИЕ\n\nДанные хранятся ${String(p.retention).toLowerCase()} либо до отзыва согласия, если отсутствует иное основание. После достижения цели данные уничтожаются или обезличиваются.\n\n9. ПРАВА СУБЪЕКТА\n\nСубъект вправе запросить сведения, уточнение, блокирование или уничтожение данных и отозвать согласие. Обращение направляется на ${l.email}.\n\n10. ЗАЩИТА И ИЗМЕНЕНИЯ\n\nОператор принимает правовые, организационные и технические меры. Актуальная редакция размещается на сайте ${l.domain}.`,
consent:`СОГЛАСИЕ НА ОБРАБОТКУ ПЕРСОНАЛЬНЫХ ДАННЫХ\n\nЯ, пользователь сайта ${l.domain}, свободно и в своём интересе даю ${l.operator} согласие на обработку данных, предоставленных через формы сайта.\n\nПеречень данных: ${l.data}.\n\nЦели: ${l.purposes}.\n\nРазрешённые действия: сбор, запись, систематизация, хранение, уточнение, использование, передача привлекаемым лицам, блокирование и уничтожение.\n\nСрок: до достижения целей или до отзыва, если отсутствует иное законное основание.\n\nСогласие можно отозвать обращением на ${l.email}. Нажатие кнопки отправки формы при установленном чекбоксе подтверждает ознакомление с Политикой и выражение согласия.\n\nШаблон нужно адаптировать под конкретную форму и состав данных.`,
cookies:`ПОЛИТИКА ИСПОЛЬЗОВАНИЯ COOKIE-ФАЙЛОВ\n\nСайт: ${l.domain}\nОператор: ${l.operator}\n\nCookie-файлы — небольшие фрагменты данных, сохраняемые браузером. Они могут использоваться для работы сайта, настроек, безопасности и аналитики.\n\n${p.useAnalytics?'По анкете используются аналитические инструменты. Перечислите реальные системы, категории cookie, сроки хранения и способы отказа.':'Сторонняя аналитика не отмечена. Проверьте фактический код сайта, виджеты и технические cookie.'}\n\nПользователь может ограничить или удалить cookie в браузере. Отключение обязательных cookie может повлиять на функции сайта.\n\nКонтакт: ${l.email}.`,
marketing:`СОГЛАСИЕ НА РЕКЛАМНЫЕ И ИНФОРМАЦИОННЫЕ СООБЩЕНИЯ\n\nЯ добровольно даю ${l.operator} согласие направлять мне информационные и рекламные сообщения по указанным каналам.\n\nСогласие является отдельным от согласия, необходимого для обработки заявки или исполнения договора. Отказ от рекламы не должен препятствовать получению основной услуги.\n\nСогласие можно отозвать через ссылку отказа либо обращением на ${l.email}.`,
request:`ЗАПРОС СУБЪЕКТА ПЕРСОНАЛЬНЫХ ДАННЫХ\n\nКому: ${l.operator}\nEmail: ${l.email}\n\nОт: __________________________________\nКонтакт для ответа: ___________________\n\nПрошу:\n[ ] предоставить информацию об обработке;\n[ ] уточнить данные;\n[ ] прекратить обработку при наличии оснований;\n[ ] удалить или уничтожить данные;\n[ ] отозвать согласие;\n[ ] иное: _____________________________.\n\nСведения для поиска данных: _______________________________.\n\nДата: __________  Подпись / подтверждение: __________\n\nОператору следует установить порядок проверки личности и исполнения обращений.`}}
function renderDocs(){const p=active();if(!p)return;const d=docs(p);$('docOutput').value=d[currentDoc];const names={policy:'Политика обработки ПД',consent:'Согласие на обработку',cookies:'Cookie-политика',marketing:'Согласие на рассылку',request:'Форма обращения субъекта'};$('docTitle').textContent=names[currentDoc]}
function renderCodes(){const p=active();if(!p)return;const d=clean(p.domain)||'example.ru';$('formCode').value=`<label class="privacy-consent">\n  <input type="checkbox" name="personal_data_consent" required>\n  <span>Я соглашаюсь с <a href="https://${d}/privacy" target="_blank">Политикой обработки персональных данных</a> и даю согласие на обработку данных.</span>\n</label>`;$('marketingCode').value=`<label class="marketing-consent">\n  <input type="checkbox" name="marketing_consent">\n  <span>Я согласен получать информационные и рекламные сообщения. Согласие добровольное и может быть отозвано.</span>\n</label>`;$('footerCode').value=`<nav class="legal-links">\n  <a href="/privacy">Политика обработки персональных данных</a>\n  <a href="/consent">Согласие на обработку данных</a>\n  <a href="/cookies">Политика cookie</a>\n</nav>`;$('cookieCode').value=`<div id="cookie-notice" hidden>\n  <p>Мы используем cookie для работы сайта${p.useAnalytics?' и аналитики':''}. Подробнее — в <a href="/cookies">Политике cookie</a>.</p>\n  <button type="button" id="cookie-accept">Принять</button>\n</div>\n<script>\n(function(){\n  var key='cookie-consent-v1';\n  var box=document.getElementById('cookie-notice');\n  if(!localStorage.getItem(key)) box.hidden=false;\n  document.getElementById('cookie-accept').onclick=function(){\n    localStorage.setItem(key,new Date().toISOString());\n    box.hidden=true;\n  };\n})();\n<\/script>`}
function applyPreset(){const p=active(),t=$('siteType').value,presets={landing:{collectName:true,collectPhone:true,useAnalytics:true,useMessengers:true},store:{collectName:true,collectPhone:true,collectEmail:true,collectAddress:true,collectPayment:true,useAnalytics:true,useCrm:true},education:{collectName:true,collectPhone:true,collectEmail:true,hasChildren:true,useMessengers:true},community:{collectName:true,collectEmail:true,collectAccount:true,useAnalytics:true},media:{collectEmail:true,useAnalytics:true,useNewsletter:true}};checks.forEach(id=>p[id]=false);Object.assign(p,presets[t]||{});toForm(p);fromForm();toast('Профиль применён')}
function applyBrand(){$('brandName').textContent=branding.whiteLabelName;$('footerBrand').textContent=branding.whiteLabelName+(branding.agencyName?' · '+branding.agencyName:'')+' · local-first';$('whiteLabelName').value=branding.whiteLabelName;$('agencyName').value=branding.agencyName;$('agencyContact').value=branding.agencyContact;$('accentColor').value=branding.accentColor;document.documentElement.style.setProperty('--accent',branding.accentColor)}
function renderAll(){renderProjects();toForm(active());renderAudit();renderDocs();renderCodes()}
function download(name,text,type='text/plain;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function copy(text){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.append(ta);ta.select();document.execCommand('copy');ta.remove()}}
fields.forEach(id=>{const e=$(id);if(e)e.addEventListener(checks.has(id)?'change':'input',fromForm)});
qsa('.doc-btn').forEach(b=>b.onclick=()=>{qsa('.doc-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentDoc=b.dataset.doc;renderDocs()});
qsa('.copy-code').forEach(b=>b.onclick=async()=>{await copy($(b.dataset.target).value);toast('Код скопирован')});
$('newBtn').onclick=()=>{fromForm();const p=blank();projects.unshift(p);activeId=p.id;persist();renderAll();toast('Проект создан')};
$('cloneBtn').onclick=()=>{const p=active(),c=JSON.parse(JSON.stringify(p));c.id=uid();c.projectName=(p.projectName||'Проект')+' — копия';projects.unshift(c);activeId=c.id;persist();renderAll();toast('Проект скопирован')};
$('deleteBtn').onclick=()=>{if(projects.length===1)return toast('Должен остаться один проект');if(!confirm('Удалить проект?'))return;projects=projects.filter(p=>p.id!==activeId);activeId=projects[0].id;persist();renderAll()};
$('demoBtn').onclick=()=>{const p=demo();projects.unshift(p);activeId=p.id;persist();renderAll();toast('Демо загружено')};
$('saveBtn').onclick=()=>{fromForm();toast('Сохранено в браузере')};
$('presetBtn').onclick=applyPreset;
$('copyDocBtn').onclick=async()=>{await copy($('docOutput').value);toast('Документ скопирован')};
$('txtBtn').onclick=()=>download(currentDoc+'-'+(active()?.domain||'site')+'.txt',$('docOutput').value);
$('printBtn').onclick=()=>window.print();
$('csvBtn').onclick=()=>{const s=analyze(active()),rows=[['Статус','Пункт','Рекомендация'],...s.issues.map(x=>[x.sev,x.title,x.text]),...s.ok.map(x=>['ok',x,'Пункт отражён в анкете'])];download('siteguard-checklist.csv','\uFEFF'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8')};
$('exportBtn').onclick=()=>{fromForm();download('siteguard-project-'+(active()?.domain||'export')+'.json',JSON.stringify({project:active(),branding,generatedAt:new Date().toISOString()},null,2),'application/json')};
$('brandBtn').onclick=()=>{branding={whiteLabelName:clean($('whiteLabelName').value)||'SiteGuard 152',agencyName:clean($('agencyName').value),agencyContact:clean($('agencyContact').value),accentColor:$('accentColor').value};persist();applyBrand();toast('Брендинг применён')};
read();
